comment  git cicd becaue render deployment

diff --git a/.github/workflows/backend_deploy.yml b/.github/workflows/backend_deploy.yml
--- a/.github/workflows/backend_deploy.yml
+++ b/.github/workflows/backend_deploy.yml
@@ -1,136 +1,136 @@
-name: Backend Deploy
+# name: Backend Deploy
 
-on:
-  push:
-    branches: [main]
-    tags:
-      - "v*"
-    paths:
-      - "backend/**"
+# on:
+#   push:
+#     branches: [main]
+#     tags:
+#       - "v*"
+#     paths:
+#       - "backend/**"
 
-env:
-  BACKEND_IMAGE: ${{ secrets.BACKEND_IMAGE }}
-  DOCKER_NETWORK: ${{ secrets.DOCKER_NETWORK }}
-jobs:
-
-
+# env:
+#   BACKEND_IMAGE: ${{ secrets.BACKEND_IMAGE }}
+#   DOCKER_NETWORK: ${{ secrets.DOCKER_NETWORK }}
+# jobs:
 
 
 
-  build-backend:
+
+
+#   build-backend:
   
-    runs-on: ubuntu-latest
-    outputs:
-      imagetag: ${{ steps.image_tag.outputs.imagetag }}
+#     runs-on: ubuntu-latest
+#     outputs:
+#       imagetag: ${{ steps.image_tag.outputs.imagetag }}
 
-    steps:
-      - uses: actions/checkout@v5
-      - uses: docker/login-action@v3
-        with:
-          username: ${{ secrets.DOCKERHUB_USERNAME }}
-          password: ${{ secrets.DOCKERHUB_TOKEN }}
+#     steps:
+#       - uses: actions/checkout@v5
+#       - uses: docker/login-action@v3
+#         with:
+#           username: ${{ secrets.DOCKERHUB_USERNAME }}
+#           password: ${{ secrets.DOCKERHUB_TOKEN }}
 
-      - name: Set up QEMU
-        uses: docker/setup-qemu-action@v3
+#       - name: Set up QEMU
+#         uses: docker/setup-qemu-action@v3
 
-      - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v3
+#       - name: Set up Docker Buildx
+#         uses: docker/setup-buildx-action@v3
 
-      - name: Extract metadata (tag, labels)
-        id: meta
-        uses: docker/metadata-action@v5.9.0
-        with:
-          images: ${{env.BACKEND_IMAGE}}
-          tags: |
-            type=semver,pattern={{version}}
-            type=sha,format=long
-            type=raw,value=latest
+#       - name: Extract metadata (tag, labels)
+#         id: meta
+#         uses: docker/metadata-action@v5.9.0
+#         with:
+#           images: ${{env.BACKEND_IMAGE}}
+#           tags: |
+#             type=semver,pattern={{version}}
+#             type=sha,format=long
+#             type=raw,value=latest
 
-      - name: Build and push image
-        uses: docker/build-push-action@v6
-        with:
-          context: ./backend
-          push: true
-          tags: ${{ steps.meta.outputs.tags }}
-          labels: ${{ steps.meta.outputs.labels }}
+#       - name: Build and push image
+#         uses: docker/build-push-action@v6
+#         with:
+#           context: ./backend
+#           push: true
+#           tags: ${{ steps.meta.outputs.tags }}
+#           labels: ${{ steps.meta.outputs.labels }}
 
-      - name: Deploy backend (first tag only)
-        id: image_tag
-        run: |
-          # Get first tag from metadata (split by newline)
-          FIRST_TAG=$(echo "${{ steps.meta.outputs.tag-names }}" | head -n1)
-          if [ -z "$FIRST_TAG" ]; then
-            echo "No tag found, exiting."
-            exit 1
-          fi
-          echo "Deploying tag: $FIRST_TAG"
-          echo "imagetag=$FIRST_TAG" >> $GITHUB_OUTPUT
+#       - name: Deploy backend (first tag only)
+#         id: image_tag
+#         run: |
+#           # Get first tag from metadata (split by newline)
+#           FIRST_TAG=$(echo "${{ steps.meta.outputs.tag-names }}" | head -n1)
+#           if [ -z "$FIRST_TAG" ]; then
+#             echo "No tag found, exiting."
+#             exit 1
+#           fi
+#           echo "Deploying tag: $FIRST_TAG"
+#           echo "imagetag=$FIRST_TAG" >> $GITHUB_OUTPUT
 
-  deploy-backend:
-    needs: build-backend
-    runs-on: ubuntu-latest
-    environment: production
-    steps:
-      - name: check image tag
-        run: |
-          echo ${{ needs.build-backend.outputs.imagetag }}
-          echo "Deploying imagetag=${{env.BACKEND_IMAGE}}:${{ needs.build-backend.outputs.imagetag }}"
+#   deploy-backend:
+#     needs: build-backend
+#     runs-on: ubuntu-latest
+#     environment: production
+#     steps:
+#       - name: check image tag
+#         run: |
+#           echo ${{ needs.build-backend.outputs.imagetag }}
+#           echo "Deploying imagetag=${{env.BACKEND_IMAGE}}:${{ needs.build-backend.outputs.imagetag }}"
 
-      - name: SSH into host
-        uses: appleboy/ssh-action@v1
-        with:
-          host: ${{ secrets.HOST }}
-          username: ${{ secrets.USER }}
-          key: ${{ secrets.SSH_KEY }}
-          envs: BACKEND_IMAGE
-          script: |
-            # Pull new image as green
-            echo "$BACKEND_IMAGE:${{ needs.build-backend.outputs.imagetag }}"
+#       - name: SSH into host
+#         uses: appleboy/ssh-action@v1
+#         with:
+#           host: ${{ secrets.HOST }}
+#           username: ${{ secrets.USER }}
+#           key: ${{ secrets.SSH_KEY }}
+#           envs: BACKEND_IMAGE
+#           script: |
+#             # Pull new image as green
+#             echo "$BACKEND_IMAGE:${{ needs.build-backend.outputs.imagetag }}"
 
-            sudo docker pull $BACKEND_IMAGE:${{ needs.build-backend.outputs.imagetag }}
+#             sudo docker pull $BACKEND_IMAGE:${{ needs.build-backend.outputs.imagetag }}
 
-            LIVE=$(grep -oP 'default\s+\Kbackend_(blue|green)' /etc/nginx/conf.d/app.conf)
-            echo "LIVE IS: $LIVE"
+#             LIVE=$(grep -oP 'default\s+\Kbackend_(blue|green)' /etc/nginx/conf.d/app.conf)
+#             echo "LIVE IS: $LIVE"
 
-            if [ "$LIVE" = "backend_blue" ]; then
-              TARGET="backend_green"
-              PORT=3002
-            else
-              TARGET="backend_blue"
-              PORT=3001
-            fi
+#             if [ "$LIVE" = "backend_blue" ]; then
+#               TARGET="backend_green"
+#               PORT=3002
+#             else
+#               TARGET="backend_blue"
+#               PORT=3001
+#             fi
 
 
-            echo "Deploy TARGET: $TARGET on PORT: $PORT"
+#             echo "Deploy TARGET: $TARGET on PORT: $PORT"
 
-            sudo docker run -d \
-              --name $TARGET \
-              --env-file /home/ubuntu/deploy/.backend.env \
-              --network ${{ secrets.DOCKER_NETWORK}} \
-              --network-alias backend \
-              -p $PORT:3000 \
-              $BACKEND_IMAGE:${{ needs.build-backend.outputs.imagetag }}
+#             sudo docker run -d \
+#               --name $TARGET \
+#               --env-file /home/ubuntu/deploy/.backend.env \
+#               --network ${{ secrets.DOCKER_NETWORK}} \
+#               --network-alias backend \
+#               -p $PORT:3000 \
+#               $BACKEND_IMAGE:${{ needs.build-backend.outputs.imagetag }}
 
-            # Health check loop (max 30s)
-            for i in {1..30}; do
-              if curl -sSf http://localhost:$PORT/health; then break; fi;
-              sleep 1;
-            done
+#             # Health check loop (max 30s)
+#             for i in {1..30}; do
+#               if curl -sSf http://localhost:$PORT/health; then break; fi;
+#               sleep 1;
+#             done
 
-            echo "Switch Nginx upstream $LIVE to $TARGET"
-            sudo sed -i "s/default $LIVE;/default $TARGET;/" /etc/nginx/conf.d/app.conf
-            echo "nginx reloading"
+#             echo "Switch Nginx upstream $LIVE to $TARGET"
+#             sudo sed -i "s/default $LIVE;/default $TARGET;/" /etc/nginx/conf.d/app.conf
+#             echo "nginx reloading"
 
-            sudo nginx -s reload
-            echo "sleeping for 100s"
+#             sudo nginx -s reload
+#             echo "sleeping for 100s"
 
-            sleep 60
+#             sleep 60
 
-            sudo nginx -t && sudo nginx -s reload
+#             sudo nginx -t && sudo nginx -s reload
 
-            echo "removing old and in active contanier"
-            sudo docker stop $LIVE || true 
-            sudo docker rm $LIVE || true
+#             echo "removing old and in active contanier"
+#             sudo docker stop $LIVE || true 
+#             sudo docker rm $LIVE || true
 
-            echo "Cleanup unused Docker images ✔️"
-            sudo docker system prune -f
+#             echo "Cleanup unused Docker images ✔️"
+#             sudo docker system prune -f
